name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6

      - name: Login to GitHub Container Registry
        run: docker login --username ONDubovckaya --password ${{ secrets.GH_PAT }} ghcr.io
      
      - name: Grant execute permission for mvn
        run: chmod +x mvn

      - name: Build a container image from our Spring Boot app using Paketo.io / Cloud Native Build Packs
        run: mvn spring-boot:build-image --imageName=$IMAGE_NAME
        
      - name: Tag & publish to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/ONDubovickaya/$IMAGE_NAME
          VERSION=latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
